spring.application.name=ms-produto

spring.profiles.active=test
spring.jpa.open-in-view=false

#              http://localhost:8080/swagger-ui/index.html
# JSON format: http://localhost:8080/v3/api-docs


